### PR TITLE
JAV-221 make vertx eventloop thread name related to vertx name

### PR DESCRIPTION
**Pull request by wujimin**
previous name is "vert.x-eventloop-thread-{number}"
new name is "{name}-vert.x-eventloop-thread-{number}"

### CODE REVIEW

**Comment by wujimin** [comment]
yes
but vertx did not provide mechanism to do this
and we have automatic test case to ensure this is no problem.

**Comment by liubao68** [comment]
return Vertx.vertx(vertxOptions) is a factory method , after change, we new a object our self, most of time UT can not guarantee this

**Comment by wujimin** [comment]
UT do not  care for this , thread  name only  for  runtime.

**Comment by wujimin** [comment]
just  only  one  test case check  the  thread name , this  case  added  in this PR

**Pull request merged**
